name: detekt

on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
     - cron: '00 10 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 detekt:
   runs-on: ubuntu-latest

   steps:
     - name: "checkout"
       uses: actions/checkout@v2

     - name: "detekt"
       uses: natiginfo/action-detekt-all@1.21.0
